### ISSUE TITLE
cuBlas输出结果错误

### ISSUE THREAD

**Issue by mutou-wl** [KnowingNothing/MatmulTutorial#1]
你好！我将您的代码运行在4090上，当我想打印cuBlas结果时，输出全为0，不知道这是什么原因？
cudaMemcpy(hC, dC, M * N * 2, cudaMemcpyDeviceToHost);

**Comment by mutou-wl** [comment]
找到问题，nvidia官网对于cublas  Compute Type 为float关键字为CUBLAS_COMPUTE_32F，并且alpha and beta要float类型

**Comment by KnowingNothing** [comment]
已修改。谢谢指正
