### ISSUE TITLE
Does CUTLASS + Reply means Cute implementation / matmul_v16 in your pic?

### ISSUE THREAD

**Issue by Toudsour** [KnowingNothing/MatmulTutorial#3]
I found matmul_v16 is implemented by cute. I wonder what's its performance. Is it comparable to the CUTLASS?

Appreciate for your answer！

**Comment by KnowingNothing** [comment]
Do you mean `Relay+CUTLASS`? It's in [this file](https://github.com/KnowingNothing/MatmulTutorial/blob/main/examples/matmul/tvm/relay_matmul_cutlass.py).

**Comment by Toudsour** [comment]
Thanks for your answer! Closed the issue.
BTW, thanks for your tutorial. It helped me implement a simple GEMM with tensor core.
