### ISSUE TITLE
fp8 compute error

### ISSUE THREAD

**Issue by rightchose** [KnowingNothing/MatmulTutorial#4]
I try https://github.com/KnowingNothing/MatmulTutorial/blob/main/examples/matmul/this-fp8/matmul-fp8-v0.cu in hopper, but get "an illegal memory access was encountered".

**Comment by KnowingNothing** [comment]
FP8 is not ready. I have no access to Hopper devices. I tried to use 4090 but FP8 is not supported by ptxas so far. I can't continue developing this kernel until I get one Hopper device.
If you have access to Hopper devices, feel free to continue developing this kernel and contribution is highly welcomed!

**Comment by rightchose** [comment]
It's seem that https://github.com/KnowingNothing/MatmulTutorial/blob/6cba2fb4cb5a14b1b9e8978bd05dcc758fa5f111/examples/matmul/this-fp8/matmul-fp8-v0.cu#L345C4-L345C5 have a wrong offset

**Comment by rightchose** [comment]
In addition, I would like to ask you about the wgmma matrix layout descriptor. I have some question here:
    1. For matrix B, your code loads it from gmem to smem and rearranges it, changing the column-major of the previous element level into the column major of the core matrix level. Is it right? 
    2. for this fig https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#wgmma-64n16-core-matrices-b,I think it describes how the data of matrix b is arranged on smem, where the number represents the element index on gmem, is it right?

**Comment by KnowingNothing** [comment]
I have gotten access to one H100 machine and fixed the FP8 kernel. Althought the performance is bad, the compute results are correct now. As for your questions,
1. My kernel assumes matrix B is column-major in gmem, and when loading it from gmem, I change the layout to [n/8,k/16,8,16] in smem, which corresponds to the core matrix layout. Each core matrix is also column-major for matrix B.
2. Yes, the numbers in the figure are the index of elements.

**Comment by rightchose** [comment]
now, the code is right, but for this commit，https://github.com/KnowingNothing/MatmulTutorial/commit/89bde23e0768d04acf70a15bb7e9d8852554c743，Why you swap the value of leading dimension and stride dimension? For matrix B, each core matrix is column-major with shape of 16x8.  From nv docuemnt, leading dimension is for K Dimension, It seems leadding dimension should be  16, and stride dimension offset is 8?

**Comment by KnowingNothing** [comment]
Honestly speaking, I am not sure about this. I have tried different settings for these two paramters and the current setting is the only one that works. I need more time to understand why.

**Comment by rightchose** [comment]
> Thank you very much!
